# Generated by Django 3.2.9 on 2021-11-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(help_text='Enter your tag')),
                ('words', models.TextField(help_text='Enter your words')),
            ],
        ),
    ]
